update investment_analytics.staging.staging_financials
set item = case
when item = 'Revenues' then 'revenues'
when item = 'GrossProfit' then 'gross_profit'
when item = 'OperatingIncomeLoss' then 'operating_income'
when item = 'NetIncomeLoss' then 'net_income'
when item = 'EarningsPerShareBasic' then 'basic_earnings_per_share'
when item = 'EarningsPerShareDiluted' then 'diluted_earnings_per_share'
when item = 'OperatingExpenses' then 'operating_expenses'
when item = 'IncomeTaxExpenseBenefit' then 'income_tax_benefit'
when item = 'Assets' then 'assets'
when item = 'Liabilities' then 'liabilities'
when item = 'StockholdersEquity' then 'equity'
when item = 'AssetsCurrent' then 'current_assets'
when item = 'LiabilitiesCurrent' then 'current_liabilities'
when item = 'LiabilitiesNoncurrent' then 'noncurrent_liabilities'
when item = 'NetCashProvidedByUsedInOperatingActivities' then 'net_cash_flow_from_operating_activities'
when item = 'NetCashProvidedByUsedInInvestingActivities' then 'net_cash_flow_from_investing_activities'
when item = 'NetCashProvidedByUsedInFinancingActivities' then 'net_cash_flow_from_financing_activities';